"""InFormha exercise catalog.

Stable exercise metadata only. Sets, reps, duration, rest and load belong to the
workout plan generated by the coach and are intentionally not stored here.
"""

GROUPS = (
    ("Petto", (
        {"name": "Chest press alla macchina", "guide_id": "chest"},
        {"name": "Aperture / pec deck alla macchina", "guide_id": "pec_fly"},
        {"name": "Piegamenti a terra (Push-up)", "guide_id": "push_up"},
    )),
    ("Schiena", (
        {"name": "Lat machine al petto", "guide_id": "lat"},
        {"name": "Lat machine presa stretta", "guide_id": "lat_close_grip"},
        {"name": "Lat machine presa inversa", "guide_id": "lat_reverse_grip"},
        {"name": "Pull-down a braccia tese", "guide_id": "straight_arm_pulldown"},
        {"name": "Rematore monobraccio con manubrio su panca", "guide_id": "one_arm_dumbbell_row"},
    )),
    ("Spalle", (
        {"name": "Shoulder press con manubri", "guide_id": "dumbbell_shoulder_press"},
        {"name": "Alzate laterali con manubri", "guide_id": "dumbbell_lateral_raise"},
        {"name": "Face pull alla Fassi", "guide_id": "face_pull"},
        {"name": "Reverse fly con manubri", "guide_id": "dumbbell_reverse_fly"},
    )),
    ("Tricipiti", (
        {"name": "Push-down tricipiti con corda", "guide_id": "pushdown"},
        {"name": "Push-down tricipiti con barra corta leggermente piegata", "guide_id": "triceps_short_bar_pushdown"},
        {"name": "Estensione tricipiti sopra la testa", "guide_id": "overhead_triceps_extension"},
        {"name": "Push-down tricipiti monobraccio", "guide_id": "single_arm_triceps_pushdown"},
    )),
    ("Bicipiti e avambracci", (
        {"name": "Curl con manubri", "guide_id": "dumbbell_curl"},
        {"name": "Hammer curl con manubri", "guide_id": "dumbbell_hammer_curl"},
        {"name": "Reverse curl con manubri", "guide_id": "reverse_curl"},
    )),
    ("Gambe / quadricipiti", (
        {"name": "Goblet squat a box/panca", "guide_id": "goblet_squat"},
        {"name": "Leg extension alla macchina", "guide_id": "leg_extension"},
        {"name": "Split squat con manubri", "guide_id": "dumbbell_split_squat"},
        {"name": "Step-up sul gradino", "guide_id": "step_up"},
    )),
    ("Femorali / catena posteriore", (
        {"name": "Stacco rumeno con manubri", "guide_id": "romanian_deadlift"},
        {"name": "Stacco rumeno a una gamba con manubrio", "guide_id": "single_leg_romanian_deadlift"},
        {"name": "Hamstring walkout", "guide_id": "hamstring_walkout"},
    )),
    ("Glutei", (
        {"name": "Ponte glutei / Hip thrust", "guide_id": "glute_bridge"},
        {"name": "Glute kickback a corpo libero", "guide_id": "bodyweight_glute_kickback"},
    )),
    ("Polpacci", (
        {"name": "Calf raise in piedi", "guide_id": "calf_raise"},
        {"name": "Calf raise a una gamba sul gradino", "guide_id": "single_leg_step_calf_raise"},
        {"name": "Seated calf raise con manubrio sulla panca", "guide_id": "seated_dumbbell_calf_raise"},
    )),
    ("Core", (
        {"name": "Plank", "guide_id": "plank"},
        {"name": "Crunch su panca inclinata", "guide_id": "incline_bench_crunch"},
        {"name": "Heel taps / Tocchi ai talloni", "guide_id": "heel_taps"},
        {"name": "Crunch inverso", "guide_id": "reverse_crunch"},
    )),
    ("Cardio", (
        {"name": "Tapis roulant Fassi", "guide_id": "treadmill"},
        {"name": "Mini stepper", "guide_id": "stepper"},
    )),
)

def all_exercises(): return tuple(exercise for _, exercises in GROUPS for exercise in exercises)
def exercise_count(): return len(all_exercises())
def guide_ids(): return tuple(exercise["guide_id"] for exercise in all_exercises())

assert exercise_count() == 37, f"Expected 37 exercises, got {exercise_count()}"
assert len(set(guide_ids())) == 37, "Each exercise must have a unique guide_id"
