// InFormha adaptive planner - 36 supported exercises + treadmill
(function(){
 if(typeof IF50==='undefined')return;
 const LIB={
  Petto:[['chest','Chest press alla macchina','chest','plates'],['pec_fly','Aperture / pec deck alla macchina','pec_fly','plates'],['push_up','Piegamenti a terra (Push-up)','push_up','bodyweight']],
  Schiena:[['lat','Lat machine al petto','lat','plates'],['lat_close_grip','Lat machine presa stretta','lat_close_grip','plates'],['lat_reverse_grip','Lat machine presa inversa','lat_reverse_grip','plates'],['straight_arm_pulldown','Pull-down a braccia tese','straight_arm_pulldown','plates'],['one_arm_dumbbell_row','Rematore monobraccio con manubrio su panca','one_arm_dumbbell_row','kg']],
  Spalle:[['dumbbell_shoulder_press','Shoulder press con manubri','dumbbell_shoulder_press','kg'],['dumbbell_lateral_raise','Alzate laterali con manubri','dumbbell_lateral_raise','kg'],['face_pull','Face pull alla Fassi','face_pull','plates'],['dumbbell_reverse_fly','Reverse fly con manubri','dumbbell_reverse_fly','kg']],
  Tricipiti:[['pushdown','Push-down tricipiti con corda','pushdown','plates'],['triceps_short_bar_pushdown','Push-down tricipiti con barra corta leggermente piegata','triceps_short_bar_pushdown','plates'],['overhead_triceps_extension','Estensione tricipiti sopra la testa','overhead_triceps_extension','plates'],['single_arm_triceps_pushdown','Push-down tricipiti monobraccio','single_arm_triceps_pushdown','plates']],
  Bicipiti:[['dumbbell_curl','Curl con manubri','dumbbell_curl','kg'],['dumbbell_hammer_curl','Hammer curl con manubri','dumbbell_hammer_curl','kg'],['reverse_curl','Reverse curl con manubri','reverse_curl','kg']],
  Gambe:[['goblet_squat','Goblet squat a box/panca','goblet_squat','kg'],['leg_extension','Leg extension alla macchina','leg_extension','plates'],['dumbbell_split_squat','Split squat con manubri','dumbbell_split_squat','kg'],['step_up','Step-up sul gradino','step_up','bodyweight']],
  Femorali:[['romanian_deadlift','Stacco rumeno con manubri','romanian_deadlift','kg'],['single_leg_romanian_deadlift','Stacco rumeno a una gamba con manubrio','single_leg_romanian_deadlift','kg'],['hamstring_walkout','Hamstring walkout','hamstring_walkout','bodyweight']],
  Glutei:[['glute_bridge','Ponte glutei / Hip thrust','glute_bridge','bodyweight'],['bodyweight_glute_kickback','Glute kickback a corpo libero','bodyweight_glute_kickback','bodyweight']],
  Polpacci:[['calf_raise','Calf raise in piedi','calf_raise','bodyweight'],['single_leg_step_calf_raise','Calf raise a una gamba sul gradino','single_leg_step_calf_raise','bodyweight'],['seated_dumbbell_calf_raise','Seated calf raise con manubrio sulla panca','seated_dumbbell_calf_raise','kg']],
  Core:[['plank','Plank','plank','bodyweight'],['incline_bench_crunch','Crunch su panca inclinata','incline_bench_crunch','bodyweight'],['heel_taps','Heel taps / Tocchi ai talloni','heel_taps','bodyweight'],['reverse_crunch','Crunch inverso','reverse_crunch','bodyweight']],
  Mobilità:[['mobility_upper','Mobilità dinamica parte alta','mobility_upper','bodyweight'],['mobility_back_lats','Mobilità dinamica schiena e dorsali','mobility_back_lats','bodyweight'],['mobility_hips','Mobilità dinamica anche','mobility_hips','bodyweight'],['mobility_ankles','Mobilità dinamica caviglie','mobility_ankles','bodyweight'],['mobility_trunk','Mobilità dinamica tronco','mobility_trunk','bodyweight']],
  Stretching:[['stretch_chest','Stretching petto','stretch_chest','bodyweight'],['stretch_back_lats','Stretching schiena e dorsali','stretch_back_lats','bodyweight'],['stretch_shoulders_triceps','Stretching spalle e tricipiti','stretch_shoulders_triceps','bodyweight'],['stretch_biceps_forearms','Stretching bicipiti e avambracci','stretch_biceps_forearms','bodyweight'],['stretch_hamstrings_glutes','Stretching femorali e glutei','stretch_hamstrings_glutes','bodyweight'],['stretch_calves','Stretching polpacci','stretch_calves','bodyweight'],['stretch_trunk_core','Stretching tronco e core','stretch_trunk_core','bodyweight']]
 };
 window.IF72_LIBRARY=Object.fromEntries(Object.entries(LIB).flatMap(([group,items])=>items.map(x=>{const p=prescription(group,x[0]);return [x[0],{id:x[0],name:x[1],guide:x[2],loadType:x[3],group,equipment:x[3]==='kg'?'Manubri':x[3]==='plates'?'Fassi':'Corpo libero',sets:p.sets,reps:p.reps,rest:p.rest,repType:p.repType,perSide:!!p.perSide,mobility:group==='Mobilità',stretching:group==='Stretching',seconds:(group==='Mobilità'||group==='Stretching')?(p.reps||30):null}]})));
 function painBlocks(group){const p=String(IF50.pain||'').toLowerCase();if(!p||p==='nessuno')return false;if(p.includes('ginoc'))return ['Gambe','Polpacci'].includes(group);if(p.includes('spalla'))return ['Petto','Spalle','Tricipiti'].includes(group);if(p.includes('schiena'))return ['Schiena','Femorali'].includes(group);return false}
 function prescription(group,id){let sets=IF50.energy==='Bassa'?2:3,reps=10,rest=['Gambe','Femorali','Petto','Schiena'].includes(group)?120:90;if(IF50.time<=30)sets=2;if(id==='plank')return {sets,reps:30,rest:60,repType:'seconds'};if(group==='Stretching')return {sets:1,reps:30,rest:15,repType:'seconds',perSide:['stretch_shoulders_triceps','stretch_biceps_forearms','stretch_hamstrings_glutes','stretch_calves'].includes(id)};if(group==='Mobilità')return {sets:1,reps:30,rest:15,repType:'seconds',perSide:['mobility_hips','mobility_ankles'].includes(id)};return {sets,reps,rest,repType:'reps'}}
 function pickExercise(group,index){const a=LIB[group]||[];if(!a.length)return null;const x=a[index%a.length],p=prescription(group,x[0]);return {id:x[0],name:x[1],guide:x[2],loadType:x[3],group,priority:index<2?'Essenziale':'Utile',...p}}
 window.if50BuildPlan=function(){IF50.intent='Coach automatico';IF50.focus='Automatico';const ranked=(IF50.adaptiveGroups||['Petto','Schiena','Gambe','Femorali','Spalle','Glutei','Core','Tricipiti','Bicipiti','Polpacci']).filter(g=>!painBlocks(g));const target=IF50.time<=20?2:IF50.time<=30?3:IF50.time<50?4:5,primary=ranked[0],companions={Petto:'Tricipiti',Schiena:'Bicipiti',Spalle:'Tricipiti',Gambe:'Polpacci',Femorali:'Glutei',Glutei:'Femorali',Tricipiti:'Petto',Bicipiti:'Schiena',Core:'Petto',Polpacci:'Gambe'},companion=companions[primary],choices=[];if(primary){choices.push(pickExercise(primary,0));if((LIB[primary]||[]).length>1)choices.push(pickExercise(primary,1))}if(companion&&ranked.includes(companion)&&!painBlocks(companion))choices.push(pickExercise(companion,0));if(IF50.time>=50&&ranked.includes('Core')&&primary!=='Core')choices.push(pickExercise('Core',0));for(const g of ranked){if(choices.length>=target)break;if(g===primary||g===companion||g==='Core')continue;choices.push(pickExercise(g,0))}IF50.plan=choices.filter(Boolean).slice(0,target);if(IF50.treadmill_choice==='Sì'&&Number(IF50.treadmillMinutes)>0)IF50.plan.unshift({id:'treadmill',name:'Tapis roulant Fassi',group:'Cardio',priority:'Cardio',sets:1,reps:null,rest:0,guide:'treadmill',cardio:true,duration:Number(IF50.treadmillMinutes),minutes:Number(IF50.treadmillMinutes),protocol:{duration:Number(IF50.treadmillMinutes),phases:[]}});return IF50.plan};
 window.if50SetRow=function(ex,n){const bodyweight=ex.loadType==='bodyweight',seconds=ex.repType==='seconds',unit=seconds?(ex.perSide?'Secondi per lato':'Secondi'):'Ripetizioni';return `<div class="setrow"><b>${n}</b>${bodyweight?`<div class="field" style="display:flex;align-items:center;justify-content:center;color:var(--m)">Corpo libero</div>`:`<input id="if50w_${ex.id}_${n}" placeholder="${ex.loadType==='plates'?'Piastre':'kg'}" inputmode="decimal">`}<input id="if50r_${ex.id}_${n}" value="${ex.reps}" inputmode="numeric" aria-label="${unit}" placeholder="${unit}"><button id="if50c_${ex.id}_${n}" class="check" onclick="if50CompleteSet('${ex.id}',${n})">✓</button></div>`};
 window.if50CompleteSet=async function(id,n){const ex=(IF50.plan||[]).find(x=>x.id===id);if(!ex||ex.cardio)return;const reps=if50Num(`if50r_${id}_${n}`),inp=document.getElementById(`if50w_${id}_${n}`),fatigue=document.getElementById(`if50f_${id}`)?.value||'Giusta';let weight=if50Num(`if50w_${id}_${n}`);if(reps===null){toast(ex.repType==='seconds'?'Inserisci i secondi':'Inserisci le ripetizioni');return}if(ex.loadType==='plates'){if(weight===null||weight<1){toast('Per la Fassi inserisci almeno 1 piastra');return}weight=Math.round(weight);if(inp)inp.value=weight}else if(ex.loadType==='kg'){if(weight===null||weight<0){toast('Inserisci il carico in kg');return}}else weight=null;try{const out=await api('api/set',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({workout_id:currentWorkoutId,workout_title:'Seduta adattata',exercise:ex.name,set_no:n,weight,reps,fatigue,rest_sec:ex.rest})});currentWorkoutId=out.workout_id;const b=document.getElementById(`if50c_${id}_${n}`);if(b){b.classList.add('done');b.textContent='✓'}if(typeof if50Progress==='function')if50Progress(id);startTimer(fatigue==='Al limite'?Math.max(ex.rest,120):ex.rest);go('recovery')}catch(e){toast(e.message||'Errore salvataggio')}};
 window.if50Status=async function(id,status,priority,btn){const ex=(IF50.plan||[]).find(x=>x.id===id);btn?.parentElement?.querySelectorAll('button').forEach(b=>b.classList.toggle('on',b===btn));try{await api('api/coach/exercise-status',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({workout_id:currentWorkoutId,exercise:ex?.name||'Cardio',priority,status})})}catch(e){}};
 console.log('[INFORMHA_ADAPTIVE_LIBRARY] library49=1 bodyweight_no_load=1 plank_seconds=1 calf_loads_correct=1 timed_mobility_stretching=1 defaults_complete=1 focused_block=1 primary_pair=1 companion=1 core_at_50=1');
})();