let currentFatigue="Giusta", currentWorkoutId=null, timerInt=null;
function api(path,opts={}){return fetch(path,opts).then(async r=>{const j=await r.json();if(!r.ok)throw new Error(j.error||'Errore');return j})}
function go(page){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));const el=document.querySelector(`[data-page="${page}"]`);if(el)el.classList.add('active');document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('on',b.dataset.nav===page));window.scrollTo({top:0,behavior:'smooth'});if(page==='nutrition')loadNutrition()}
function toast(t){const d=document.createElement('div');d.className='toast';d.textContent=t;document.body.appendChild(d);setTimeout(()=>d.remove(),1800)}
function pick(b){const c=b.closest('.choice');if(c)c.querySelectorAll('button').forEach(x=>x.classList.remove('on'));b.classList.add('on')}
function fatigue(b,v){currentFatigue=v;document.querySelectorAll('#fatigue button').forEach(x=>x.classList.remove('on'));b.classList.add('on')}
function num(id){const el=document.getElementById(id);if(!el)return null;const v=parseFloat((el.value||'').replace(',','.'));return Number.isFinite(v)?v:null}
async function completeSet(btn,n){btn.classList.add('done');const out=await api('api/set',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({workout_id:currentWorkoutId,workout_title:'Petto + Tricipiti',exercise:'Chest press ai cavi',set_no:n,weight:num('w'+n),reps:num('r'+n),fatigue:currentFatigue,rest_sec:90})});currentWorkoutId=out.workout_id;startTimer(currentFatigue==='Al limite'?120:90);go('recovery')}
function startTimer(sec){clearInterval(timerInt);let left=sec,total=sec;const draw=()=>{let m=Math.floor(left/60),s=left%60;document.getElementById('timer').textContent=String(m).padStart(2,'0')+':'+String(s).padStart(2,'0');document.getElementById('timerbar').style.width=(left/total*100)+'%'};draw();timerInt=setInterval(()=>{left--;draw();if(left<=0){clearInterval(timerInt);document.getElementById('timer').textContent='VAI!'}},1000)}
async function saveMeasurement(){await api('api/measurement',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({weight_kg:num('mWeight'),waist_cm:num('mWaist'),chest_cm:num('mChest'),arm_r_cm:num('mArmR'),arm_l_cm:num('mArmL')})});toast('Misure salvate');await load()}
function fmt(v,u){return(v===null||v===undefined)?'—':`${String(Math.round(v*10)/10).replace('.',',')}${u?' '+u:''}`}
function hv(x){return x&&x.value!==null&&x.value!==undefined?fmt(x.value,x.unit):'—'}
function findMeasure(label){return [...document.querySelectorAll('.measure span')].find(x=>x.textContent.trim()===label)?.parentElement||null}
function renderHealth(h){if(!h||!h.connected)return;const d=h.data||{};if(d.weight&&d.weight.value!=null){document.getElementById('homeWeight').textContent=hv(d.weight);document.getElementById('profileWeight').textContent=hv(d.weight)}const home=document.querySelector('[data-page="home"]');if(home&&!document.getElementById('healthToday')){const card=document.createElement('div');card.className='card';card.id='healthToday';card.innerHTML=`<div class="ey">Salute oggi · HealthSync</div><div class="measure"><span>Passi</span><b>${hv(d.steps)}</b></div><div class="measure"><span>Battito</span><b>${hv(d.heart_rate)}</b></div><div class="measure"><span>HRV</span><b>${hv(d.hrv)}</b></div><div class="measure"><span>VO₂ max</span><b>${hv(d.vo2_max)}</b></div>`;home.appendChild(card)}const p=findMeasure('Passi medi');if(p){p.querySelector('span').textContent='Passi oggi';p.querySelector('b').textContent=hv(d.steps)}}
function renderNutrition(n){const t=n.totals||{};const set=(id,val,unit)=>{const e=document.getElementById(id);if(e)e.textContent=fmt(val||0,unit)};set('nutCalories',t.calories,'kcal');set('nutProtein',t.protein_g,'g');set('nutCarbs',t.carbs_g,'g');set('nutFat',t.fat_g,'g');set('nutWater',t.water_ml,'ml');const list=document.getElementById('mealList');if(!list)return;const rows=n.entries||[];if(!rows.length){list.innerHTML='Nessun alimento registrato oggi.';return}list.innerHTML=rows.map(r=>`<div class="measure"><span><b>${r.meal}</b><br><small>${r.name}${r.quantity_g?' · '+fmt(r.quantity_g,'g'):''}</small></span><b>${r.calories?fmt(r.calories,'kcal'):r.water_ml?fmt(r.water_ml,'ml'):'—'}</b></div>`).join('')}
async function loadNutrition(){try{renderNutrition(await api('api/nutrition/today'));const hs=await api('api/homestock/status');const e=document.getElementById('homeStockStatus');if(e)e.textContent=hs.message||'In attesa del collegamento.'}catch(e){toast('Errore dati alimentazione')}}
async function addWater(ml){try{const out=await api('api/nutrition/water',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ml})});renderNutrition(out.today);toast(`Aggiunti ${ml} ml`)}catch(e){toast(e.message)}}
async function saveFood(){const name=document.getElementById('foodName').value.trim();if(!name){toast('Inserisci il nome alimento');return}const body={meal:document.getElementById('foodMeal').value,name,brand:document.getElementById('foodBrand').value.trim()||null,quantity_g:num('foodQty'),calories:num('foodCal'),protein_g:num('foodProtein'),carbs_g:num('foodCarbs'),fat_g:num('foodFat'),source:'manual'};try{await api('api/nutrition/entry',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});toast('Alimento aggiunto');go('nutrition')}catch(e){toast(e.message)}}
async function uploadPlatePhoto(){const input=document.getElementById('platePhoto'),status=document.getElementById('platePhotoStatus');if(!input.files||!input.files[0]){toast('Scatta o scegli una foto');return}const fd=new FormData();fd.append('photo',input.files[0]);status.textContent='Salvataggio foto…';try{const out=await api('api/nutrition/plate-photo',{method:'POST',body:fd});status.textContent=out.message;toast('Foto salvata')}catch(e){status.textContent=e.message}}
async function lookupBarcode(){const code=document.getElementById('barcodeValue').value.trim();if(!code){toast('Inserisci o scansiona un barcode');return}const hs=await api('api/homestock/status');if(!hs.connected){toast('HomeStock non è ancora collegato');return}}
async function load(){try{const [s,h,n]=await Promise.all([api('api/state'),api('api/healthsync'),api('api/nutrition/today')]),p=s.profile,m=s.measurement||{};document.getElementById('homeWeight').textContent=fmt(m.weight_kg||p.weight_kg,'kg');document.getElementById('pWeight').textContent=fmt(m.weight_kg,'kg');document.getElementById('pWaist').textContent=fmt(m.waist_cm,'cm');document.getElementById('pChest').textContent=fmt(m.chest_cm,'cm');document.getElementById('pArmR').textContent=fmt(m.arm_r_cm,'cm');document.getElementById('pArmL').textContent=fmt(m.arm_l_cm,'cm');document.getElementById('profileName').textContent=p.name;document.getElementById('profileHeight').textContent=fmt(p.height_cm,'cm');document.getElementById('profileWeight').textContent=fmt(m.weight_kg||p.weight_kg,'kg');document.getElementById('profileGoal').textContent=p.goal;document.getElementById('profileLevel').textContent=p.level;document.getElementById('version').textContent=s.version;renderHealth(h);renderNutrition(n)}catch(e){toast('Backend non raggiungibile')}}
load();
