let currentFatigue="Giusta", currentWorkoutId=null, timerInt=null;
function api(path,opts={}){return fetch(path,opts).then(async r=>{const j=await r.json();if(!r.ok)throw new Error(j.error||'Errore');return j})}
function navRoot(page){if(['checkin','recovery','endworkout','summary','exerciseguide'].includes(page))return 'workout';if(['foodsearch','barcode','platephoto'].includes(page))return 'nutrition';if(['progress','coach','profiledata','connections'].includes(page))return 'profile';return page}
function go(page,updateHash=true){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));const el=document.querySelector(`[data-page="${page}"]`);if(!el)return;el.classList.add('active');const root=navRoot(page);document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('on',b.dataset.nav===root));window.scrollTo({top:0,behavior:'smooth'});if(updateHash&&location.hash!==`#${page}`)history.replaceState(null,'',`#${page}`);if(page==='nutrition')loadNutrition()}
window.addEventListener('hashchange',()=>{const page=location.hash.replace('#','')||'home';go(page,false)})
function toast(t){const d=document.createElement('div');d.className='toast';d.textContent=t;document.body.appendChild(d);setTimeout(()=>d.remove(),1800)}
function pick(b){const c=b.closest('.choice');if(c)c.querySelectorAll('button').forEach(x=>x.classList.remove('on'));b.classList.add('on')}
function fatigue(b,v){currentFatigue=v;document.querySelectorAll('#fatigue button').forEach(x=>x.classList.remove('on'));b.classList.add('on')}
function num(id){const el=document.getElementById(id);if(!el)return null;const v=parseFloat((el.value||'').replace(',','.'));return Number.isFinite(v)?v:null}

const EXERCISE_GUIDES={
 chest:{title:'Chest press alla macchina',muscles:'Petto · tricipiti · spalle anteriori',hook:'Nessun aggancio a cavo',accessory:'Usa direttamente i due bracci press della multigym Fassi',setup:'Siediti con schiena completamente appoggiata. Regola la posizione in modo che le impugnature siano circa all’altezza del centro del petto. Piedi ben appoggiati.',steps:['Afferra le impugnature con polsi dritti.','Spingi in avanti senza sollevare le spalle.','Arriva quasi a distendere le braccia, senza bloccare con forza i gomiti.','Torna lentamente finché senti il petto allungarsi, senza far sbattere il pacco pesi.'],feel:'Devi sentire soprattutto il petto lavorare; tricipiti e parte anteriore delle spalle aiutano.',errors:['Spalle che salgono verso le orecchie','Schiena che si stacca dallo schienale','Ritorno veloce facendo sbattere i pesi','Gomiti bloccati violentemente a fine spinta']},
 lat:{title:'Lat machine al petto',muscles:'Dorsali · bicipiti · parte alta della schiena',hook:'Punto ALTO della multigym, quello sopra la testa',accessory:'Barra larga',setup:'Siediti rivolto verso la macchina. Afferra la barra con presa ampia e palmi in avanti. Petto leggermente in fuori, schiena neutra, piedi stabili.',steps:['Prima di tirare, abbassa le spalle lontano dalle orecchie.','Porta i gomiti verso il basso e leggermente indietro.','Tira la barra verso la parte alta del petto.','Risalita lenta fino quasi a distendere le braccia, mantenendo il controllo.'],feel:'Pensa di tirare con i gomiti: devi sentire la schiena larga, non solo le braccia.',errors:['Portare la barra dietro la nuca','Dondolare con il busto','Tirare solo con i bicipiti','Lasciare risalire il peso di colpo']},
 pushdown:{title:'Push-down tricipiti con corda',muscles:'Tricipiti',hook:'Punto ALTO della multigym',accessory:'Corda nera a due estremità',setup:'In piedi davanti alla macchina. Piedi alla larghezza delle anche, busto alto. Gomiti aderenti ai fianchi e leggermente davanti al busto.',steps:['Impugna le due estremità della corda con presa neutra.','Tieni fermi i gomiti e spingi la corda verso il basso.','In fondo distendi le braccia e separa leggermente le estremità della corda.','Ritorna lentamente finché gli avambracci risalgono, senza muovere i gomiti.'],feel:'La tensione deve stare soprattutto dietro al braccio, sul tricipite.',errors:['Gomiti che vanno avanti e indietro','Spalle sollevate','Usare il peso del corpo per spingere','Risalita troppo rapida']},
 curl:{title:'Curl bicipiti al cavo basso',muscles:'Bicipiti · avambracci',hook:'Punto BASSO SOTTO IL SEDILE: moschettone della carrucola bassa centrale',accessory:'Barra corta angolata',setup:'Posizionati davanti alla macchina, centrato rispetto al sedile. La barra parte dal cavo che esce SOTTO il sedile, non lateralmente. Schiena dritta, petto aperto, gomiti vicini al corpo.',steps:['Aggancia la barra corta al moschettone sotto il sedile.','Impugna la barra con palmi verso l’alto e braccia quasi distese.','Senza spostare i gomiti, piega le braccia e porta la barra verso l’addome/parte bassa del petto.','Scendi lentamente fino quasi a distendere i gomiti e ripeti.'],feel:'Devi sentire il bicipite contrarsi senza dover muovere schiena o spalle.',errors:['Usare un aggancio laterale: sulla tua macchina va usato quello sotto il sedile','Dondolare con il busto','Gomiti che avanzano durante la salita','Lasciare cadere il peso in discesa']}
};

function installExerciseGuides(){
 const app=document.querySelector('.app');
 if(app&&!document.querySelector('[data-page="exerciseguide"]'))app.insertAdjacentHTML('beforeend',`<section class="page" data-page="exerciseguide"><div class="ey">Guida esercizio · attrezzatura reale</div><h1 id="guideTitle">Esercizio</h1><div class="status" id="guideMuscles"></div><div class="card"><div class="ey">1 · Dove agganciare</div><h2 id="guideHook"></h2><div class="sub">Controlla sempre che il moschettone sia completamente chiuso prima di iniziare.</div></div><div class="card"><div class="ey">2 · Accessorio</div><h2 id="guideAccessory"></h2></div><div class="card"><div class="ey">3 · Preparazione</div><div class="sub" id="guideSetup"></div></div><div class="card"><div class="ey">4 · Movimento</div><div id="guideSteps"></div></div><div class="card coach"><div class="ey">Cosa devi sentire</div><div class="sub" id="guideFeel"></div></div><div class="card"><div class="ey">⚠ Errori da evitare</div><div id="guideErrors"></div></div><button class="btn" onclick="go('workout')">Ho capito · torna all'esercizio</button></section>`);
 const workout=document.querySelector('[data-page="workout"]');
 const ph=workout?.querySelector('.placeholder');
 if(ph){ph.classList.remove('placeholder');ph.classList.add('card');ph.innerHTML=`<div class="ey">Guide sulla tua attrezzatura Fassi</div><h2>Prima prova virtuale</h2><div class="sub">Apri una guida: ti indica punto di aggancio, accessorio, posizione, movimento, cosa sentire ed errori da evitare.</div><div class="grid2" style="margin-top:12px"><button class="btn secondary" onclick="openGuide('chest')">Chest press</button><button class="btn secondary" onclick="openGuide('lat')">Lat machine</button><button class="btn secondary" onclick="openGuide('pushdown')">Tricipiti corda</button><button class="btn secondary" onclick="openGuide('curl')">Curl bicipiti</button></div><div class="sub" style="margin-top:10px">Per il curl: <b>aggancio basso sotto il sedile</b>, non laterale.</div>`}
 const h2=workout?.querySelector('.card h2');if(h2&&h2.textContent.includes('Chest press'))h2.textContent='Chest press alla macchina';
 ['w1','w2','w3'].forEach(id=>{const e=document.getElementById(id);if(e){e.value='';e.placeholder='Livello pin';e.title='Livello numerato del pacco pesi'}});
}
function openGuide(id){const g=EXERCISE_GUIDES[id];if(!g)return;document.getElementById('guideTitle').textContent=g.title;document.getElementById('guideMuscles').textContent=g.muscles;document.getElementById('guideHook').textContent=g.hook;document.getElementById('guideAccessory').textContent=g.accessory;document.getElementById('guideSetup').textContent=g.setup;document.getElementById('guideSteps').innerHTML=g.steps.map((s,i)=>`<div class="measure"><span><b>${i+1}</b> · ${s}</span></div>`).join('');document.getElementById('guideFeel').textContent=g.feel;document.getElementById('guideErrors').innerHTML=g.errors.map(s=>`<div class="measure"><span>✕ ${s}</span></div>`).join('');go('exerciseguide')}

async function completeSet(btn,n){btn.classList.add('done');const out=await api('api/set',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({workout_id:currentWorkoutId,workout_title:'Petto + Tricipiti',exercise:'Chest press alla macchina',set_no:n,weight:num('w'+n),reps:num('r'+n),fatigue:currentFatigue,rest_sec:90})});currentWorkoutId=out.workout_id;startTimer(currentFatigue==='Al limite'?120:90);go('recovery')}
function startTimer(sec){clearInterval(timerInt);let left=sec,total=sec;const draw=()=>{let m=Math.floor(left/60),s=left%60;document.getElementById('timer').textContent=String(m).padStart(2,'0')+':'+String(s).padStart(2,'0');document.getElementById('timerbar').style.width=(left/total*100)+'%'};draw();timerInt=setInterval(()=>{left--;draw();if(left<=0){clearInterval(timerInt);document.getElementById('timer').textContent='VAI!'}},1000)}
async function saveMeasurement(){await api('api/measurement',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({weight_kg:num('mWeight'),waist_cm:num('mWaist'),chest_cm:num('mChest'),arm_r_cm:num('mArmR'),arm_l_cm:num('mArmL')})});toast('Misure salvate');await load()}
function fmt(v,u){return(v===null||v===undefined)?'—':`${String(Math.round(v*10)/10).replace('.',',')}${u?' '+u:''}`}
function hv(x){return x&&x.value!==null&&x.value!==undefined?fmt(x.value,x.unit):'—'}
function findMeasure(label){return [...document.querySelectorAll('.measure span')].find(x=>x.textContent.trim()===label)?.parentElement||null}
function renderHealth(h){if(!h||!h.connected)return;const d=h.data||{};if(d.weight&&d.weight.value!=null){document.getElementById('homeWeight').textContent=hv(d.weight);document.getElementById('profileWeight').textContent=hv(d.weight)}const home=document.querySelector('[data-page="home"]');if(home&&!document.getElementById('healthToday')){const card=document.createElement('div');card.className='card';card.id='healthToday';card.innerHTML=`<div class="ey">Salute oggi · HealthSync</div><div class="measure"><span>Passi</span><b>${hv(d.steps)}</b></div><div class="measure"><span>Battito</span><b>${hv(d.heart_rate)}</b></div><div class="measure"><span>HRV</span><b>${hv(d.hrv)}</b></div><div class="measure"><span>VO₂ max</span><b>${hv(d.vo2_max)}</b></div>`;home.appendChild(card)}const p=findMeasure('Passi medi');if(p){p.querySelector('span').textContent='Passi oggi';p.querySelector('b').textContent=hv(d.steps)}}
function renderNutrition(n){const t=n.totals||{};const set=(id,val,unit)=>{const e=document.getElementById(id);if(e)e.textContent=fmt(val||0,unit)};set('nutCalories',t.calories,'kcal');set('nutProtein',t.protein_g,'g');set('nutCarbs',t.carbs_g,'g');set('nutFat',t.fat_g,'g');set('nutWater',t.water_ml,'ml');const list=document.getElementById('mealList');if(!list)return;const rows=n.entries||[];if(!rows.length){list.innerHTML='Nessun alimento registrato oggi.';return}list.innerHTML=rows.map(r=>`<div class="measure"><span><b>${r.meal}</b><br><small>${r.name}${r.quantity_g?' · '+fmt(r.quantity_g,'g'):''}</small></span><b>${r.calories?fmt(r.calories,'kcal'):r.water_ml?fmt(r.water_ml,'ml'):'—'}</b></div>`).join('')}
async function loadNutrition(){try{renderNutrition(await api('api/nutrition/today'));const hs=await api('api/homestock/status');const e=document.getElementById('homeStockStatus');if(e)e.textContent=hs.message||'In attesa del collegamento.'}catch(e){toast('Errore dati alimentazione')}}
async function addWater(ml){try{const out=await api('api/nutrition/water',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ml})});renderNutrition(out.today);toast(`Aggiunti ${ml} ml`)}catch(e){toast(e.message)}}
async function saveFood(){const name=document.getElementById('foodName').value.trim();if(!name){toast('Inserisci il nome alimento');return}const body={meal:document.getElementById('foodMeal').value,name,brand:document.getElementById('foodBrand').value.trim()||null,quantity_g:num('foodQty'),calories:num('foodCal'),protein_g:num('foodProtein'),carbs_g:num('foodCarbs'),fat_g:num('foodFat'),source:'manual'};try{await api('api/nutrition/entry',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});toast('Alimento aggiunto');go('nutrition')}catch(e){toast(e.message)}}
async function uploadPlatePhoto(){const input=document.getElementById('platePhoto'),status=document.getElementById('platePhotoStatus');if(!input.files||!input.files[0]){toast('Scatta o scegli una foto');return}const fd=new FormData();fd.append('photo',input.files[0]);status.textContent='Salvataggio foto…';try{const out=await api('api/nutrition/plate-photo',{method:'POST',body:fd});status.textContent=out.message;toast('Foto salvata')}catch(e){status.textContent=e.message}}
async function lookupBarcode(){const code=document.getElementById('barcodeValue').value.trim();if(!code){toast('Inserisci o scansiona un barcode');return}const hs=await api('api/homestock/status');if(!hs.connected){toast('HomeStock non è ancora collegato');return}}
async function load(){try{const [s,h,n]=await Promise.all([api('api/state'),api('api/healthsync'),api('api/nutrition/today')]),p=s.profile,m=s.measurement||{};document.getElementById('homeWeight').textContent=fmt(m.weight_kg||p.weight_kg,'kg');document.getElementById('pWeight').textContent=fmt(m.weight_kg,'kg');document.getElementById('pWaist').textContent=fmt(m.waist_cm,'cm');document.getElementById('pChest').textContent=fmt(m.chest_cm,'cm');document.getElementById('pArmR').textContent=fmt(m.arm_r_cm,'cm');document.getElementById('pArmL').textContent=fmt(m.arm_l_cm,'cm');document.getElementById('profileName').textContent=p.name;document.getElementById('profileHeight').textContent=fmt(p.height_cm,'cm');document.getElementById('profileWeight').textContent=fmt(m.weight_kg||p.weight_kg,'kg');document.getElementById('profileGoal').textContent=p.goal;document.getElementById('profileLevel').textContent=p.level;document.getElementById('version').textContent=s.version;renderHealth(h);renderNutrition(n)}catch(e){toast('Backend non raggiungibile')}}
installExerciseGuides();
load().finally(()=>{const initial=location.hash.replace('#','')||'home';go(initial,false)});
