let currentFatigue="Giusta", currentWorkoutId=null, timerInt=null;
function api(path,opts={}){return fetch(path,opts).then(r=>r.json())}
function go(page){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));const el=document.querySelector(`[data-page="${page}"]`);if(el)el.classList.add('active');document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('on',b.dataset.nav===page));window.scrollTo({top:0,behavior:'smooth'})}
function toast(t){const d=document.createElement('div');d.className='toast';d.textContent=t;document.body.appendChild(d);setTimeout(()=>d.remove(),1800)}
function pick(b){const c=b.closest('.choice');if(c)c.querySelectorAll('button').forEach(x=>x.classList.remove('on'));b.classList.add('on')}
function fatigue(b,v){currentFatigue=v;document.querySelectorAll('#fatigue button').forEach(x=>x.classList.remove('on'));b.classList.add('on')}
function num(id){const el=document.getElementById(id);if(!el)return null;const v=parseFloat((el.value||'').replace(',','.'));return Number.isFinite(v)?v:null}
async function completeSet(btn,n){btn.classList.add('done');const out=await api('api/set',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({workout_id:currentWorkoutId,workout_title:'Petto + Tricipiti',exercise:'Chest press ai cavi',set_no:n,weight:num('w'+n),reps:num('r'+n),fatigue:currentFatigue,rest_sec:90})});currentWorkoutId=out.workout_id;startTimer(currentFatigue==='Al limite'?120:90);go('recovery')}
function startTimer(sec){clearInterval(timerInt);let left=sec,total=sec;const draw=()=>{let m=Math.floor(left/60),s=left%60;document.getElementById('timer').textContent=String(m).padStart(2,'0')+':'+String(s).padStart(2,'0');document.getElementById('timerbar').style.width=(left/total*100)+'%'};draw();timerInt=setInterval(()=>{left--;draw();if(left<=0){clearInterval(timerInt);document.getElementById('timer').textContent='VAI!'}},1000)}
async function saveMeasurement(){await api('api/measurement',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({weight_kg:num('mWeight'),waist_cm:num('mWaist'),chest_cm:num('mChest'),arm_r_cm:num('mArmR'),arm_l_cm:num('mArmL')})});toast('Misure salvate');await load()}
async function saveCardio(){await api('api/cardio',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({activity:'Tapis roulant',duration_min:num('cDuration'),avg_hr:num('cAvg'),max_hr:num('cMax'),calories:num('cCal')})});toast('Cardio salvato')}
function fmt(v,u){return(v===null||v===undefined)?'—':`${String(v).replace('.',',')} ${u}`}
async function load(){try{const s=await api('api/state'),p=s.profile,m=s.measurement||{};document.getElementById('homeWeight').textContent=fmt(m.weight_kg||p.weight_kg,'kg');document.getElementById('pWeight').textContent=fmt(m.weight_kg,'kg');document.getElementById('pWaist').textContent=fmt(m.waist_cm,'cm');document.getElementById('pChest').textContent=fmt(m.chest_cm,'cm');document.getElementById('pArmR').textContent=fmt(m.arm_r_cm,'cm');document.getElementById('pArmL').textContent=fmt(m.arm_l_cm,'cm');document.getElementById('profileName').textContent=p.name;document.getElementById('profileHeight').textContent=fmt(p.height_cm,'cm');document.getElementById('profileWeight').textContent=fmt(m.weight_kg||p.weight_kg,'kg');document.getElementById('profileGoal').textContent=p.goal;document.getElementById('profileLevel').textContent=p.level;document.getElementById('version').textContent=s.version}catch(e){toast('Backend non raggiungibile')}}
load();
