// InFormha 0.4.0 - guide persistenti caricate dall'utente
const GUIDE_LABELS_040={chest:'Chest press',lat:'Lat machine',pushdown:'Push-down corda',curl:'Curl cavo basso'};
function visualBlock(id){return `<div class="guide-photo-wrap"><div id="guideMissing-${id}" class="guide-missing" style="display:none"><b>Guida HD non ancora caricata</b><div class="sub">Vai in Altro → Connessioni e dispositivi → Gestione guide.</div></div><img class="guide-photo guide-local" src="guide-local/${id}?t=${Date.now()}" alt="Guida visuale ${GUIDES[id]?.title||id}" onerror="this.style.display='none';document.getElementById('guideMissing-${id}').style.display='block'" onclick="openGuideZoom040('${id}')"><div class="guide-photo-note">Tocca l'immagine per aprirla grande</div></div>`}
function openGuideZoom040(id){const src=`guide-local/${id}?t=${Date.now()}`;let m=document.getElementById('guideZoom040');if(!m){m=document.createElement('div');m.id='guideZoom040';m.className='guide-zoom040';m.innerHTML=`<div class="guide-zoom040-bar"><button onclick="closeGuideZoom040()">✕ Chiudi</button></div><div class="guide-zoom040-stage"><img id="guideZoom040Img"></div>`;document.body.appendChild(m)}document.getElementById('guideZoom040Img').src=src;m.classList.add('open');document.body.style.overflow='hidden'}
function closeGuideZoom040(){document.getElementById('guideZoom040')?.classList.remove('open');document.body.style.overflow=''}
async function refreshGuideManager(){try{const d=await api('api/guides');for(const id of Object.keys(GUIDE_LABELS_040)){const e=document.getElementById(`guideStatus-${id}`),g=d.guides?.[id];if(e)e.textContent=g?.installed?`✓ ${g.filename} · ${Math.round((g.size||0)/1024)} KB`:'Nessuna immagine caricata'}}catch(e){toast('Errore stato guide')}}
async function uploadGuide040(id){const input=document.getElementById(`guideFile-${id}`);if(!input?.files?.[0]){toast('Scegli un’immagine');return}const fd=new FormData();fd.append('image',input.files[0]);try{await api(`api/guides/${id}`,{method:'POST',body:fd});toast('Guida salvata');await refreshGuideManager()}catch(e){toast(e.message)}}
(function(){const s=document.createElement('style');s.textContent=`.guide-missing{padding:28px 18px;border:1px dashed #49515c;border-radius:18px;text-align:center;background:#11151a}.guide-photo.guide-local{width:100%;height:auto;display:block;border-radius:20px;background:#0d1014}.guide-zoom040{display:none;position:fixed;inset:0;background:#000;z-index:10050}.guide-zoom040.open{display:flex;flex-direction:column}.guide-zoom040-bar{padding:10px;background:#0b0d10}.guide-zoom040-bar button{padding:10px 14px;border-radius:12px;background:#1a1f25;color:#fff;border:1px solid #39414a}.guide-zoom040-stage{flex:1;overflow:auto;display:flex;align-items:flex-start;justify-content:center}.guide-zoom040-stage img{display:block;max-width:none;width:100%;height:auto}.guide-manager-row{margin-top:12px;padding:14px;border:1px solid #2e343c;border-radius:16px}.guide-manager-row input{width:100%;margin:9px 0}`;document.head.appendChild(s);
const conn=document.querySelector('[data-page="connections"]');if(conn&&!document.getElementById('guideManager040')){const back=[...conn.querySelectorAll('button')].find(b=>b.textContent.includes('Indietro'));const box=document.createElement('div');box.id='guideManager040';box.className='card';box.innerHTML=`<div class="ey">Gestione guide</div><h2>Immagini esercizi</h2><div class="sub">Le immagini vengono salvate nei dati persistenti di InFormha e restano anche dopo gli aggiornamenti.</div>${Object.entries(GUIDE_LABELS_040).map(([id,label])=>`<div class="guide-manager-row"><b>${label}</b><div class="sub" id="guideStatus-${id}">Controllo…</div><input id="guideFile-${id}" type="file" accept="image/jpeg,image/png,image/webp"><button class="btn secondary" onclick="uploadGuide040('${id}')">Carica / sostituisci</button></div>`).join('')}`;if(back)conn.insertBefore(box,back);else conn.appendChild(box);}
refreshGuideManager();})();
