// InFormha 0.9.41 - mostra tutte le metriche Health Auto Export, anche non previste
(function(){
  const esc=v=>{const d=document.createElement('div');d.textContent=String(v??'');return d.innerHTML};
  const fmtName=k=>String(k||'').replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
  const fmt=x=>!x||x.value===null||x.value===undefined||x.value===''?'—':`${esc(x.value)}${x.unit?` ${esc(x.unit)}`:''}`;
  const fmtTs=raw=>{if(!raw)return'—';const d=new Date(raw);return Number.isNaN(d.getTime())?esc(raw):d.toLocaleString('it-IT',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'})};
  const ageClass=raw=>{if(!raw)return'';const t=new Date(raw).getTime();if(!Number.isFinite(t))return'';const h=(Date.now()-t)/3600000;return h<=2?'green':h<=24?'':'if941Old'};
  const LABELS={step_count:'Passi',walking_running_distance:'Distanza cammino/corsa',flights_climbed:'Piani saliti',walking_speed:'Velocità cammino',walking_step_length:'Lunghezza passo',walking_double_support_percentage:'Doppio appoggio',walking_asymmetry_percentage:'Asimmetria cammino',active_energy:'Calorie attive',basal_energy_burned:'Energia basale',apple_exercise_time:'Tempo esercizio',apple_stand_hour:'Ore in piedi',apple_stand_time:'Tempo in piedi',physical_effort:'Sforzo fisico',resting_heart_rate:'FC a riposo',heart_rate_min:'FC minima',heart_rate_average:'FC media',heart_rate_max:'FC massima',heart_rate_variability:'HRV',walking_heart_rate_average:'FC media cammino',vo2_max:'VO₂ max',blood_oxygen_saturation:'Saturazione ossigeno',body_mass:'Peso',body_mass_index:'BMI',body_fat_percentage:'Massa grassa',lean_body_mass:'Massa magra',sleep_analysis:'Sonno',dietary_water:'Acqua',dietary_energy:'Calorie alimentari',environmental_audio_exposure:'Esposizione audio ambientale'};
  const GROUPS=[
    ['Attività e camminata',k=>/(step|walk|running|distance|flight|speed|asymmetry|support)/.test(k)],
    ['Energia e movimento',k=>/(energy|exercise|stand|effort)/.test(k)&&!/(dietary)/.test(k)],
    ['Cuore e fitness',k=>/(heart|hrv|vo2|oxygen|respirat|cardio)/.test(k)],
    ['Corpo',k=>/(body_mass|weight|bmi|body_fat|lean_body|waist|height)/.test(k)],
    ['Sonno',k=>/(sleep)/.test(k)],
    ['Nutrizione e idratazione',k=>/(dietary|water|protein|carb|fat|fiber|sugar|caffeine|vitamin|mineral)/.test(k)],
    ['Altri dati',k=>true]
  ];
  function appleCard(){const page=document.querySelector('[data-page="connections"]');if(!page)return null;return [...page.querySelectorAll(':scope > .card')].find(c=>{const t=(c.textContent||'').toLowerCase();return t.includes('apple salute')&&(t.includes('health auto export')||t.includes('healthsync'))})||null;}
  function newest(metrics){let best=null;for(const m of Object.values(metrics||{})){const raw=m?.last_updated;if(!raw)continue;const t=new Date(raw).getTime();if(Number.isFinite(t)&&(!best||t>best.t))best={t,raw};}return best?.raw||null;}
  function row(k,m){return `<div class="if941Row"><div><span>${esc(LABELS[k]||fmtName(k))}</span><b>${fmt(m)}</b></div><small class="${ageClass(m?.last_updated)}">${fmtTs(m?.last_updated)}</small><small class="if941Entity">hae.homeassistant_${esc(k)}</small></div>`;}
  function grouped(metrics){const remaining=new Set(Object.keys(metrics||{}));const out=[];for(const [title,test] of GROUPS){const keys=[];for(const k of [...remaining]){if(test(k)){keys.push(k);remaining.delete(k);if(title==='Altri dati')continue;}}if(keys.length)out.push(`<details class="if941Group"><summary>${esc(title)} <span>(${keys.length})</span></summary>${keys.sort().map(k=>row(k,metrics[k])).join('')}</details>`);if(title==='Altri dati')break;}return out.join('');}
  async function load(){const host=document.getElementById('if941HealthHost');if(!host)return;host.innerHTML='<div class="sub">Lettura completa dati Apple Salute…</div>';try{const d=await api('api/healthsync'),metrics=d.metrics||{},connected=!!d.connected,found=Object.keys(metrics).length,last=newest(metrics);host.innerHTML=`<div class="measure"><span>Collegamento</span><b class="${connected?'green':''}">${connected?'● Attivo':'● Nessun dato'}</b></div><div class="measure"><span>Dati ricevuti</span><b>${found}</b></div><div class="measure"><span>Ultima sincronizzazione</span><b class="${ageClass(last)}">${fmtTs(last)}</b></div><div class="sub" style="margin:10px 0">Mostro tutte le entità Health Auto Export ricevute, incluse quelle non ancora classificate da InFormha.</div>${grouped(metrics)||'<div class="sub">Nessun dato Health Auto Export disponibile.</div>'}<button class="btn secondary" type="button" id="if941Refresh">Aggiorna dati</button>`;document.getElementById('if941Refresh')?.addEventListener('click',load);}catch(e){host.innerHTML=`<div class="sub">${esc(e.message||'Errore lettura dati Apple Salute')}</div>`;}}
  function install(){const card=appleCard();if(!card)return;document.getElementById('if940HealthHost')?.remove();document.getElementById('if940Hint')?.remove();document.getElementById('if935HealthHost')?.remove();document.getElementById('if935Hint')?.remove();if(card.dataset.if941Ready==='1')return;card.dataset.if941Ready='1';card.style.cursor='pointer';const body=document.createElement('div');body.id='if941HealthHost';body.className='hide';body.style.marginTop='14px';card.appendChild(body);const hint=document.createElement('div');hint.id='if941Hint';hint.className='sub';hint.style.marginTop='10px';hint.textContent='Tocca per controllare tutti i dati Apple Salute ricevuti.';card.appendChild(hint);card.addEventListener('click',e=>{if(e.target.closest('button,summary,details'))return;const open=body.classList.contains('hide');body.classList.toggle('hide',!open);hint.textContent=open?'Tocca di nuovo per chiudere.':'Tocca per controllare tutti i dati Apple Salute ricevuti.';if(open)load();});}
  const css=document.createElement('style');css.textContent='#if941HealthHost{border-top:1px solid var(--ln);padding-top:12px}.if941Group{border-top:1px solid var(--ln);padding:10px 0}.if941Group summary{font-weight:700;cursor:pointer}.if941Group summary span{opacity:.6;font-weight:500}.if941Row{padding:9px 0;border-top:1px solid rgba(255,255,255,.05)}.if941Row>div{display:flex;justify-content:space-between;gap:12px;align-items:center}.if941Row small{display:block;margin-top:4px;opacity:.72}.if941Entity{font-size:11px;opacity:.45!important;word-break:break-all}.if941Old{color:#f2b84b!important}';document.head.appendChild(css);
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(install,300));else setTimeout(install,300);setTimeout(install,900);setInterval(install,2000);
  console.log('[INFORMHA_HEALTH_DASHBOARD_FIX] version=0.9.41 show_all_hae_metrics=1 dynamic_uncategorized=1');
})();
