// InFormha 0.9.98 - storico misure corporee
(function(){
 const F=[['mWeight','weight_kg','Peso','kg'],['mWaist','waist_cm','Vita','cm'],['mChest','chest_cm','Torace','cm'],['mArmR','arm_r_cm','Braccio destro','cm'],['mArmL','arm_l_cm','Braccio sinistro','cm'],['mThighR','thigh_r_cm','Coscia destra','cm'],['mThighL','thigh_l_cm','Coscia sinistra','cm']];
 const fmt=v=>v==null?'—':String(Math.round(Number(v)*10)/10).replace('.',',');
 const dat=s=>{try{return new Intl.DateTimeFormat('it-IT',{day:'numeric',month:'long',year:'numeric'}).format(new Date(s))}catch(e){return s||'—'}};
 function ensure(){const p=document.querySelector('[data-page="progress"]');if(!p)return;let w=document.getElementById('if978Measures');if(w)return;const old=[...p.querySelectorAll('.card')].find(c=>(c.querySelector('h2')?.textContent||'').includes('Aggiungi misure'));if(old)old.style.display='none';w=document.createElement('div');w.id='if978Measures';w.innerHTML=`<div class="card"><div class="ey">Nuova rilevazione</div><h2>Registra le misure di oggi</h2><div class="sub">Ogni salvataggio crea una rilevazione datata e conserva le precedenti.</div><div class="if978-grid">${F.map(([id,k,l,u])=>`<label><span>${l}</span><div><input class="field" id="${id}" inputmode="decimal" placeholder="—"><small>${u}</small></div></label>`).join('')}</div><button class="btn" onclick="if978Save()">Salva misure</button><div class="sub" id="if978Reminder"></div></div><div class="card"><div class="ey">Storico misure</div><h2>Rilevazioni precedenti</h2><div id="if978History" class="sub">Caricamento…</div></div>`;const back=[...p.querySelectorAll('button')].find(b=>(b.textContent||'').trim()==='Indietro');p.insertBefore(w,back||null)}
 function render(items,rem){ensure();const b=document.getElementById('if978History');if(b)b.innerHTML=items?.length?items.map((x,i)=>`<div class="if978-entry"><div class="if978-date"><b>${dat(x.ts)}</b>${i===0?'<span>Ultima</span>':''}</div><div class="if978-values">${[['Peso',x.weight_kg,'kg'],['Vita',x.waist_cm,'cm'],['Torace',x.chest_cm,'cm'],['Braccio DX',x.arm_r_cm,'cm'],['Braccio SX',x.arm_l_cm,'cm'],['Coscia DX',x.thigh_r_cm,'cm'],['Coscia SX',x.thigh_l_cm,'cm']].filter(v=>v[1]!=null).map(v=>`<span>${v[0]} <b>${fmt(v[1])} ${v[2]}</b></span>`).join('')}</div></div>`).join(''):'Nessuna rilevazione registrata.';const r=document.getElementById('if978Reminder');if(r&&rem)r.textContent=rem.due?'📏 Sono passati almeno 30 giorni: aggiorna le misure.':`Prossimo controllo consigliato tra circa ${Math.max(0,30-(rem.days||0))} giorni.`}
 async function load(){ensure();try{const d=await api('api/measurements-0978');render(d.items,d.reminder);try{await api('api/measurements-0978/reminder-check',{method:'POST'})}catch(e){}}catch(e){}}
 window.if978Save=async function(){const p={};F.forEach(([id,k])=>{const v=(document.getElementById(id)?.value||'').trim().replace(',','.');p[k]=v===''?null:Number(v)});try{const d=await api('api/measurements-0978',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)});toast('Misure salvate');F.forEach(([id])=>{const e=document.getElementById(id);if(e)e.value=''});render(d.items,d.reminder)}catch(e){toast(e.message||'Errore salvataggio')}};
 const s=document.createElement('style');s.textContent=`.if978-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:14px 0}.if978-grid label>span{display:block;font-size:12px;color:var(--m);margin-bottom:5px}.if978-grid label>div{position:relative}.if978-grid small{position:absolute;right:12px;top:50%;transform:translateY(-50%);color:var(--m)}.if978-entry{padding:13px 0;border-bottom:1px solid var(--ln)}.if978-date{display:flex;justify-content:space-between}.if978-date span{font-size:10px;color:var(--green2)}.if978-values{display:flex;gap:8px 14px;flex-wrap:wrap;font-size:12px;margin-top:7px}@media(max-width:600px){.if978-grid{grid-template-columns:1fr}}`;document.head.appendChild(s);const g=window.go;window.go=function(page,...a){const r=g(page,...a);if(page==='progress')setTimeout(load,80);return r};setTimeout(ensure,500);console.log('[INFORMHA_MEASUREMENTS_UI] version=0.9.98 history=1 thighs=1');
})();