// InFormha 0.10.0 - alimentazione rapida + vocale, grafica originale
(function(){
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function enhance(){const p=document.querySelector('[data-page="nutrition"]');if(!p)return;const cards=[...p.querySelectorAll('.card')];const add=cards.find(c=>(c.textContent||'').includes('Alimento / HomeStock')||(c.textContent||'').includes('Aggiungi pasto'));if(!add)return;add.dataset.if100='1';add.innerHTML=`<div class="ey">Aggiungi pasto</div><h2>Registra in pochi secondi</h2><div class="sub">Puoi parlare normalmente: InFormha prova prima a usare HomeStock e poi iCoach per stimare ciò che manca.</div><button class="btn" onclick="if100Voice()">🎙️ Dì cosa stai mangiando</button><button class="btn secondary" onclick="go('platephoto')">📷 Fai foto al pasto</button><button class="btn secondary" onclick="if100Describe()">✏️ Scrivi cosa hai mangiato</button><button class="btn secondary" onclick="go('foodsearch')">🏠 Scegli da HomeStock</button><details style="margin-top:10px"><summary class="sub">Altre opzioni</summary><button class="btn secondary" onclick="go('barcode')">▦ Scansiona barcode</button></details>`}
 function modal(){let m=document.getElementById('if100MealModal');if(m)return m;m=document.createElement('div');m.id='if100MealModal';m.className='if80-modal';m.innerHTML=`<div class="if80-sheet"><div class="row"><h2 style="flex:1">Cosa stai mangiando?</h2><button class="btn secondary if80-small" onclick="if100Close()">✕</button></div><select class="field" id="if100Meal"><option>Colazione</option><option>Pranzo</option><option>Cena</option><option>Spuntino</option></select><textarea class="field" id="if100Text" rows="4" placeholder="Es. una mozzarella, due fette di prosciutto e un pezzo di pane" style="margin-top:8px"></textarea><div id="if100VoiceState" class="sub" style="margin-top:8px"></div><button class="btn" onclick="if100Estimate()">Calcola calorie e macro</button><div id="if100Result"></div></div>`;document.body.appendChild(m);return m}
 window.if100Close=()=>document.getElementById('if100MealModal')?.classList.remove('open');
 window.if100Describe=function(){modal().classList.add('open');document.getElementById('if100VoiceState').textContent='Scrivi il pasto come lo descriveresti a voce.'};
 window.if100Voice=function(){const m=modal();m.classList.add('open');const out=document.getElementById('if100VoiceState'),ta=document.getElementById('if100Text');const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){out.textContent='Il riconoscimento vocale non è disponibile in questo browser. Puoi usare la dettatura della tastiera oppure scrivere il pasto.';ta.focus();return}const r=new SR();r.lang='it-IT';r.interimResults=true;r.continuous=false;out.textContent='🎙️ Ti ascolto… descrivi cosa stai mangiando.';r.onresult=e=>{let s='';for(let i=e.resultIndex;i<e.results.length;i++)s+=e.results[i][0].transcript;ta.value=s};r.onerror=()=>out.textContent='Non sono riuscito a capire il vocale. Riprova oppure scrivi il pasto.';r.onend=()=>{out.textContent=ta.value?'Vocale acquisito. Ora calcolo usando HomeStock + iCoach.':'Nessun testo riconosciuto.';if(ta.value.trim())if100Estimate()};r.start()};
 async function homeStockContext(text){try{const s=await api('api/homestock/status');if(!s.connected)return[];const d=await api('api/homestock/catalog');const a=Array.isArray(d)?d:(d.items||d.products||d.catalog||d.results||d.data||[]);const words=text.toLowerCase().split(/\s+/).filter(w=>w.length>3);return a.filter(x=>{const z=JSON.stringify(x).toLowerCase();return words.some(w=>z.includes(w))}).slice(0,12)}catch(e){return[]}}
 function parse(answer){const nums=String(answer||'').match(/-?\d+(?:[.,]\d+)?/g)?.map(x=>Number(x.replace(',','.')))||[];return nums.length>=4?{calories:nums[0],protein_g:nums[1],carbs_g:nums[2],fat_g:nums[3]}:null}
 window.if100Estimate=async function(){const text=(document.getElementById('if100Text')?.value||'').trim(),meal=document.getElementById('if100Meal')?.value||'Spuntino',out=document.getElementById('if100Result');if(!text){toast('Descrivi cosa stai mangiando');return}out.innerHTML='<div class="sub" style="margin-top:12px">Cerco in HomeStock e preparo la stima…</div>';const hs=await homeStockContext(text);try{const q=`Devo registrare questo pasto: ${text}. Prodotti HomeStock potenzialmente corrispondenti: ${JSON.stringify(hs).slice(0,5000)}. Usa i dati HomeStock quando sono chiaramente pertinenti; per il resto stima con porzioni italiane realistiche. Rispondi ESCLUSIVAMENTE con quattro numeri separati da | nell'ordine: kcal | proteine_g | carboidrati_g | grassi_g. Niente altro.`;const d=await api('api/ai-coach/ask',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:q})});const n=parse(d.answer);if(!n)throw new Error('Formato stima non riconosciuto');window.if100Pending={meal,source:hs.length?'voice_homestock_ai':'voice_ai',name:text,notes:'≈ Stima da descrizione vocale/testuale',...n};out.innerHTML=`<div class="card" style="margin-top:12px"><div class="ey">≈ Stima InFormha</div><h2>${Math.round(n.calories)} kcal</h2><div class="sub">Proteine ${Math.round(n.protein_g)} g · Carboidrati ${Math.round(n.carbs_g)} g · Grassi ${Math.round(n.fat_g)} g</div><div class="mini" style="margin-top:8px">${hs.length?'HomeStock + iCoach':'Stima iCoach'} · valori indicativi</div><button class="btn" onclick="if100Confirm()">Conferma e registra</button><button class="btn secondary" onclick="document.getElementById('if100Text').focus()">Correggi descrizione</button></div>`}catch(e){out.innerHTML=`<div class="sub" style="margin-top:12px">Non riesco a calcolare la stima: ${esc(e.message||'errore')}</div>`}};
 window.if100Confirm=async function(){const b=window.if100Pending;if(!b)return;try{await api('api/nutrition/entry',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});toast('Pasto registrato');if100Close();go('nutrition');setTimeout(()=>window.if80Render?.(),100)}catch(e){toast(e.message||'Errore registrazione')}};
 const old=window.if80Render;if(old)window.if80Render=async function(){const r=await old();setTimeout(enhance,10);return r};const g=window.go;if(g)window.go=function(page){const r=g.apply(this,arguments);if(page==='nutrition')setTimeout(enhance,100);return r};setInterval(()=>{if(document.querySelector('[data-page="nutrition"].active'))enhance()},1000);setTimeout(enhance,500);console.log('[INFORMHA_NUTRITION_VOICE] version=0.10.0 voice=1 homestock_first=1 ai_fallback=1 confirm_save=1 original_style=1');
})();