// InFormha 0.10.2 - flusso alimentazione definitivo
(function(){
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let rec=null,chunks=[],pending=null,timer=null,secs=0;
function ensure(){let m=document.getElementById('if102Modal');if(!m){m=document.createElement('div');m.id='if102Modal';m.className='if80-modal';m.innerHTML=`<div class="if80-sheet"><div class="row"><h2 style="flex:1">Cosa stai mangiando?</h2><button class="btn secondary if80-small" onclick="if102Close()">✕</button></div><div id="if102Start"><div class="sub">Premi il pulsante e descrivi il pasto. HomeStock viene controllato automaticamente.</div><button class="btn" onclick="if102Record()">🎙️ Registra vocale</button><button class="btn secondary" onclick="if102Photo()">📷 Fotografa il pasto</button><input id="if102Camera" type="file" accept="image/*" capture="environment" hidden onchange="if102PhotoChosen(this)"></div><div id="if102State" class="sub"></div><div id="if102Result"></div></div>`;document.body.appendChild(m)}return m}
window.if102Open=()=>{ensure().classList.add('open');document.getElementById('if102Start').style.display='block';document.getElementById('if102State').innerHTML='';document.getElementById('if102Result').innerHTML='';pending=null};window.if102Close=()=>{if(rec&&rec.state==='recording')rec.stop();clearInterval(timer);ensure().classList.remove('open')};
window.if102Record=async()=>{try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});let mime='';for(const x of ['audio/mp4','audio/webm;codecs=opus','audio/webm'])if(window.MediaRecorder?.isTypeSupported?.(x)){mime=x;break}rec=new MediaRecorder(stream,mime?{mimeType:mime}:undefined);chunks=[];rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};rec.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());clearInterval(timer);const blob=new Blob(chunks,{type:rec.mimeType||mime||'audio/mp4'});await analyzeBlob(blob,'audio')};rec.start();secs=0;document.getElementById('if102Start').style.display='none';document.getElementById('if102State').innerHTML=`<div class="if102-rec">🔴 Registrazione <b id="if102Time">0:00</b></div><button class="btn" onclick="if102Stop()">⏹ Fine registrazione</button>`;timer=setInterval(()=>{secs++;const e=document.getElementById('if102Time');if(e)e.textContent=Math.floor(secs/60)+':'+String(secs%60).padStart(2,'0')},1000)}catch(e){document.getElementById('if102State').textContent='Microfono non disponibile: '+(e.message||e)}};
window.if102Stop=()=>{if(rec&&rec.state==='recording')rec.stop()};window.if102Photo=()=>document.getElementById('if102Camera').click();window.if102PhotoChosen=async el=>{const f=el.files?.[0];if(f)await analyzeBlob(f,'photo');el.value=''};
async function analyzeBlob(blob,type){document.getElementById('if102Start').style.display='none';document.getElementById('if102State').textContent='Analizzo con iCoach e controllo HomeStock…';const fd=new FormData();fd.append(type,blob,type==='audio'?'pasto.'+(blob.type.includes('webm')?'webm':'mp4'):'pasto.jpg');try{const r=await fetch((window.INGRESS||'')+`api/nutrition/analyze-${type}`,{method:'POST',body:fd});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'Analisi non riuscita');showResult(d)}catch(e){document.getElementById('if102State').textContent='Analisi non riuscita: '+(e.message||e);document.getElementById('if102Start').style.display='block'}}
function showResult(d){pending={source:'ai_voice_photo',name:d.understood||'Pasto',calories:d.calories||0,protein_g:d.protein_g||0,carbs_g:d.carbs_g||0,fat_g:d.fat_g||0,fiber_g:d.fiber_g||0,notes:'Stima iCoach con controllo HomeStock'};document.getElementById('if102State').innerHTML='';document.getElementById('if102Result').innerHTML=`<div class="card"><div class="ey">Ho capito</div><h2>${esc(pending.name)}</h2><div class="sub">≈ ${Math.round(pending.calories)} kcal · Proteine ${Math.round(pending.protein_g)} g · Carboidrati ${Math.round(pending.carbs_g)} g · Grassi ${Math.round(pending.fat_g)} g</div>${Array.isArray(d.items)?`<div class="mini">${d.items.map(x=>esc(x.name||'')).filter(Boolean).join(' · ')}</div>`:''}</div><div class="ey">Che pasto è?</div><select class="field" id="if102Meal"><option>Colazione</option><option>Pranzo</option><option>Merenda</option><option>Cena</option><option>Spuntino</option></select><button class="btn" onclick="if102Save()">Fine · Registra pasto</button><button class="btn secondary" onclick="if102Open()">Correggi / riprova</button>`}
window.if102Save=async()=>{if(!pending)return;pending.meal=document.getElementById('if102Meal').value;try{await api('api/nutrition/entry',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(pending)});toast('Pasto registrato');if102Close();go('nutrition')}catch(e){toast(e.message||'Errore')}};
function cleanHome(){const p=document.querySelector('[data-page="nutrition"]');if(!p)return;const add=[...p.querySelectorAll('.card')].find(c=>(c.textContent||'').includes('Aggiungi pasto'));if(add)add.innerHTML=`<div class="ey">Aggiungi pasto</div><h2>Cosa stai mangiando?</h2><div class="sub">Registra il pasto a voce oppure usa la fotocamera. HomeStock lavora automaticamente dietro le quinte.</div><button class="btn" onclick="if102Open()">🎙️ Cosa stai mangiando?</button><button class="btn secondary" onclick="if102PhotoDirect()">📷 Fotografa il pasto</button>`}
window.if102PhotoDirect=()=>{if102Open();setTimeout(if102Photo,50)};
function historyPage(){let p=document.querySelector('[data-page="nutrition-history-0102"]');if(!p){p=document.createElement('section');p.className='page';p.dataset.page='nutrition-history-0102';document.querySelector('.app')?.appendChild(p)}return p}
window.if102History=async()=>{const p=historyPage();go('nutrition-history-0102');p.innerHTML='<div class="ey">Alimentazione</div><h1>Pasti registrati</h1><div class="sub">Caricamento…</div>';try{const d=await api('api/nutrition/entries'),groups={};(d.items||[]).forEach(x=>{const day=String(x.ts||'').slice(0,10);(groups[day]??=[]).push(x)});p.innerHTML=`<div class="ey">Alimentazione</div><h1>Pasti registrati</h1>${Object.entries(groups).map(([day,a])=>`<div class="card"><h2>${esc(day)}</h2>${a.map(x=>`<div class="if102-entry"><div style="flex:1"><b>${esc(x.meal)} · ${esc(x.name)}</b><div class="mini">${Math.round(x.calories||0)} kcal · P ${Math.round(x.protein_g||0)} g · C ${Math.round(x.carbs_g||0)} g · G ${Math.round(x.fat_g||0)} g</div></div><button class="if80-delete" onclick="if102Delete(${x.id})">✕</button></div>`).join('')}</div>`).join('')||'<div class="card sub">Nessun pasto registrato.</div>'}<button class="btn secondary" onclick="go('profile')">Indietro</button>`}catch(e){p.innerHTML+='<div class="card sub">Errore caricamento.</div>'}};window.if102Delete=async id=>{if(!confirm('Eliminare questo pasto?'))return;await api(`api/nutrition/entry/${id}`,{method:'DELETE'});if102History()};
function addMenu(){const profile=document.querySelector('[data-page="profile"]');if(!profile)return;const btn=[...profile.querySelectorAll('button')].find(b=>(b.textContent||'').trim()==='Alimentazione');if(!btn||btn.dataset.if102)return;btn.dataset.if102='1';btn.onclick=()=>{let p=document.querySelector('[data-page="nutrition-settings-0927"]');if(!p)return;go('nutrition-settings-0927');setTimeout(()=>{if(!document.getElementById('if102HistBtn')){const b=document.createElement('button');b.id='if102HistBtn';b.className='btn secondary';b.textContent='🍽️ Pasti registrati';b.onclick=if102History;p.querySelector('h1')?.after(b)}},80)}}
const old=window.go;if(old)window.go=function(page){const r=old.apply(this,arguments);if(page==='nutrition')setTimeout(cleanHome,140);if(page==='profile')setTimeout(addMenu,100);return r};setInterval(()=>{cleanHome();addMenu()},900);const css=document.createElement('style');css.textContent='.if102-rec{padding:18px;text-align:center;font-size:18px}.if102-entry{display:flex;gap:10px;align-items:center;padding:11px 0;border-bottom:1px solid var(--ln)}';document.head.appendChild(css);console.log('[INFORMHA_NUTRITION_FINAL] version=0.10.2 clean=1 mediarecorder=1 camera=1 history_menu=1 homestock_hidden=1');
})();