// InFormha 0.10.5 - Alimentazione authoritative renderer
(function(){
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=v=>Math.round(Number(v||0)), pct=(v,g)=>g>0?Math.min(100,Math.round(Number(v||0)/Number(g)*100)):0;
let rec=null,chunks=[],pending=null,timer=null,secs=0;
function line(label,v,g,u){return `<div class="if105-line"><div class="row"><span>${label}</span><b>${fmt(v)}${u} / ${fmt(g)}${u}</b></div><div class="if105-bar"><i style="width:${pct(v,g)}%"></i></div></div>`}
async function renderNutrition(){const p=document.querySelector('[data-page="nutrition"]');if(!p)return;let today={totals:{}},goals={};try{today=await api('api/nutrition/today')}catch(e){}try{goals=(await api('api/nutrition/goals')).goals||{}}catch(e){}const t=today.totals||{},remain=Math.max(0,Number(goals.calories||0)-Number(t.calories||0));p.innerHTML=`<div class="ey">Alimentazione</div><h1>Oggi</h1><div class="card"><div class="ey">Aggiungi pasto</div><h2>Cosa stai mangiando?</h2><div class="sub">Descrivi il pasto a voce. HomeStock viene controllato automaticamente.</div><button class="btn" onclick="if105Open()">🎙️ Cosa stai mangiando?</button><button class="btn secondary" onclick="if105PhotoDirect()">📷 Fotografa il pasto</button></div><div class="card"><div class="ey">Obiettivi di oggi</div><h2>${fmt(t.calories)} / ${fmt(goals.calories)} kcal</h2><div class="sub"><b>${fmt(remain)} kcal</b> rimanenti oggi</div><div class="if105-bar big"><i style="width:${pct(t.calories,goals.calories)}%"></i></div></div><div class="card"><div class="ey">Consiglio iCoach</div><h2>Cosa potrei mangiare?</h2><div class="sub">Suggerimenti basati su obiettivi, quanto hai già mangiato e scorte HomeStock.</div><button class="btn secondary" onclick="if105Suggest()">💡 Dammi un consiglio</button><div id="if105Suggestion"></div></div><div class="card"><div class="ey">Resoconto di oggi</div>${line('Calorie',t.calories,goals.calories,' kcal')}${line('Proteine',t.protein_g,goals.protein_g,' g')}${line('Carboidrati',t.carbs_g,goals.carbs_g,' g')}${line('Grassi',t.fat_g,goals.fat_g,' g')}</div>`}
window.loadNutrition=renderNutrition;
function ensure(){let m=document.getElementById('if105Modal');if(!m){m=document.createElement('div');m.id='if105Modal';m.className='if80-modal';m.innerHTML=`<div class="if80-sheet"><div class="row"><h2 style="flex:1">Cosa stai mangiando?</h2><button class="btn secondary if80-small" onclick="if105Close()">✕</button></div><div id="if105Start"><div class="sub">Premi Registra vocale e descrivi liberamente quello che stai mangiando.</div><button class="btn" onclick="if105Record()">🎙️ Registra vocale</button><button class="btn secondary" onclick="if105Photo()">📷 Fotografa il pasto</button><input id="if105Camera" type="file" accept="image/*" capture="environment" hidden onchange="if105PhotoChosen(this)"></div><div id="if105State" class="sub"></div><div id="if105Result"></div></div>`;document.body.appendChild(m)}return m}
window.if105Open=()=>{ensure().classList.add('open');document.getElementById('if105Start').style.display='block';document.getElementById('if105State').innerHTML='';document.getElementById('if105Result').innerHTML='';pending=null};
window.if105Close=()=>{clearInterval(timer);ensure().classList.remove('open')};
window.if105Record=async()=>{try{if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)throw new Error('Registrazione audio non supportata da questo browser');const stream=await navigator.mediaDevices.getUserMedia({audio:true});let mime='';for(const x of ['audio/mp4','audio/webm;codecs=opus','audio/webm'])if(MediaRecorder.isTypeSupported(x)){mime=x;break}rec=new MediaRecorder(stream,mime?{mimeType:mime}:undefined);chunks=[];rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};rec.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());clearInterval(timer);await analyze(new Blob(chunks,{type:rec.mimeType||mime||'audio/mp4'}),'audio')};rec.start();secs=0;document.getElementById('if105Start').style.display='none';document.getElementById('if105State').innerHTML=`<div class="if105-rec">🔴 Registrazione <b id="if105Time">0:00</b></div><button class="btn" onclick="if105Stop()">⏹ Fine registrazione</button>`;timer=setInterval(()=>{secs++;const e=document.getElementById('if105Time');if(e)e.textContent=Math.floor(secs/60)+':'+String(secs%60).padStart(2,'0')},1000)}catch(e){document.getElementById('if105State').textContent='Microfono non disponibile: '+(e.message||e)}};
window.if105Stop=()=>{if(rec&&rec.state==='recording')rec.stop()};window.if105Photo=()=>document.getElementById('if105Camera').click();window.if105PhotoDirect=()=>{if105Open();setTimeout(if105Photo,30)};window.if105PhotoChosen=async el=>{const f=el.files?.[0];if(f)await analyze(f,'photo');el.value=''};
async function analyze(blob,type){document.getElementById('if105Start').style.display='none';document.getElementById('if105State').textContent='Analizzo con iCoach e controllo HomeStock…';const fd=new FormData();fd.append(type,blob,type==='audio'?'pasto.'+(blob.type.includes('webm')?'webm':'mp4'):'pasto.jpg');try{const r=await fetch(`api/nutrition/analyze-${type}`,{method:'POST',body:fd}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'Analisi non riuscita');show(d)}catch(e){document.getElementById('if105State').textContent='Analisi non riuscita: '+(e.message||e);document.getElementById('if105Start').style.display='block'}}
function show(d){pending={source:'ai_voice_photo',name:d.understood||'Pasto',calories:d.calories||0,protein_g:d.protein_g||0,carbs_g:d.carbs_g||0,fat_g:d.fat_g||0,fiber_g:d.fiber_g||0,notes:'Stima iCoach con controllo HomeStock'};document.getElementById('if105State').innerHTML='';document.getElementById('if105Result').innerHTML=`<div class="card"><div class="ey">Ho capito</div><h2>${esc(pending.name)}</h2><div class="sub">≈ ${fmt(pending.calories)} kcal · Proteine ${fmt(pending.protein_g)} g · Carboidrati ${fmt(pending.carbs_g)} g · Grassi ${fmt(pending.fat_g)} g</div></div><div class="ey">Che pasto è?</div><select class="field" id="if105Meal"><option>Colazione</option><option>Pranzo</option><option>Merenda</option><option>Cena</option><option>Spuntino</option></select><button class="btn" onclick="if105Save()">Fine · Registra pasto</button><button class="btn secondary" onclick="if105Open()">Correggi / riprova</button>`}
window.if105Save=async()=>{if(!pending)return;pending.meal=document.getElementById('if105Meal').value;await api('api/nutrition/entry',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(pending)});toast('Pasto registrato');if105Close();await renderNutrition()};
window.if105Suggest=async()=>{const o=document.getElementById('if105Suggestion');if(!o)return;o.innerHTML='<div class="sub">Controllo HomeStock…</div>';let hs={},today={},goals={};try{hs=await api('api/homestock/catalog')}catch(e){}try{today=await api('api/nutrition/today')}catch(e){}try{goals=(await api('api/nutrition/goals')).goals||{}}catch(e){}try{const q=`Suggerisci 2 o 3 cose che potrei mangiare adesso. Obiettivi: ${JSON.stringify(goals)}. Mangiato: ${JSON.stringify(today.totals||{})}. HomeStock: ${JSON.stringify(hs).slice(0,7000)}. Dai priorità alle scorte reali e sii breve.`;const d=await api('api/ai-coach/ask',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:q})});o.innerHTML=`<div class="sub" style="white-space:pre-wrap">${esc(d.answer||'Nessun consiglio disponibile')}</div>`}catch(e){o.innerHTML='<div class="sub">Consiglio non disponibile.</div>'}};
function historyPage(){let p=document.querySelector('[data-page="nutrition-history"]');if(!p){p=document.createElement('section');p.className='page';p.dataset.page='nutrition-history';document.querySelector('.app').appendChild(p)}return p}
window.if105History=async()=>{const p=historyPage();document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));p.classList.add('active');history.replaceState(null,'','#nutrition-history');p.innerHTML='<div class="ey">Alimentazione</div><h1>Pasti registrati</h1><div class="sub">Caricamento…</div>';try{const d=await api('api/nutrition/entries'),groups={};(d.items||[]).forEach(x=>{const day=String(x.ts||'').slice(0,10);(groups[day]??=[]).push(x)});p.innerHTML=`<div class="ey">Alimentazione</div><h1>Pasti registrati</h1>${Object.entries(groups).map(([day,a])=>`<div class="card"><h2>${esc(day)}</h2>${a.map(x=>`<div class="if105-entry"><div style="flex:1"><b>${esc(x.meal)} · ${esc(x.name)}</b><div class="sub">${fmt(x.calories)} kcal · P ${fmt(x.protein_g)} g · C ${fmt(x.carbs_g)} g · G ${fmt(x.fat_g)} g</div></div><button class="if80-delete" onclick="if105Delete(${x.id})">✕</button></div>`).join('')}</div>`).join('')||'<div class="card sub">Nessun pasto registrato.</div>'}<button class="btn secondary" onclick="go('profile')">Indietro</button>`}catch(e){p.innerHTML='<div class="ey">Alimentazione</div><h1>Pasti registrati</h1><div class="card sub">Errore caricamento.</div>'}};
window.if105Delete=async id=>{if(!confirm('Eliminare questo pasto?'))return;await api(`api/nutrition/entry/${id}`,{method:'DELETE'});if105History()};
function menu(){const profile=document.querySelector('[data-page="profile"]');if(!profile)return;const old=[...profile.querySelectorAll('button')].find(b=>(b.textContent||'').trim()==='Alimentazione');if(old&&!document.getElementById('if105HistoryButton')){const b=document.createElement('button');b.id='if105HistoryButton';b.className='btn secondary';b.textContent='🍽️ Pasti registrati';b.onclick=if105History;old.insertAdjacentElement('afterend',b)}}
const originalGo=window.go;window.go=function(page){const r=originalGo.apply(this,arguments);if(page==='nutrition')renderNutrition();if(page==='profile')setTimeout(menu,0);return r};
const css=document.createElement('style');css.textContent='.if105-line{padding:9px 0}.if105-bar{height:7px;border-radius:99px;background:#090b0e;border:1px solid var(--ln);overflow:hidden;margin-top:7px}.if105-bar.big{height:10px;margin-top:12px}.if105-bar i{display:block;height:100%;background:linear-gradient(90deg,var(--green),var(--blue))}.if105-rec{padding:18px;text-align:center;font-size:18px}.if105-entry{display:flex;gap:10px;align-items:center;padding:11px 0;border-bottom:1px solid var(--ln)}';document.head.appendChild(css);menu();if(document.querySelector('[data-page="nutrition"].active'))renderNutrition();console.log('[INFORMHA_NUTRITION_FINAL] version=0.10.5 authoritative=1 mediarecorder=1 camera=1 history=1');
})();