// InFormha 0.10.1 - home Alimentazione semplificata
(function(){
 const fmt=v=>Math.round(Number(v||0));
 const pct=(v,g)=>g>0?Math.min(100,Math.round(Number(v||0)/Number(g)*100)):0;
 const line=(label,v,g,u)=>`<div class="if101-line"><div class="row"><span>${label}</span><b>${fmt(v)}${u} / ${fmt(g)}${u}</b></div><div class="if101-bar"><i style="width:${pct(v,g)}%"></i></div></div>`;
 async function render(){const p=document.querySelector('[data-page="nutrition"]');if(!p)return;let today={totals:{},entries:[]},goals={};try{today=await api('api/nutrition/today')}catch(e){}try{goals=(await api('api/nutrition/goals')).goals||{}}catch(e){}const t=today.totals||{},remaining=Math.max(0,Number(goals.calories||0)-Number(t.calories||0));p.innerHTML=`<div class="ey">Alimentazione</div><h1>Oggi</h1>
 <div class="card"><div class="ey">Aggiungi pasto</div><h2>Cosa stai mangiando?</h2><div class="sub">Parla a InFormha: HomeStock viene controllato automaticamente e iCoach completa la stima.</div><button class="btn" onclick="if101OpenMeal()">🎙️ Cosa stai mangiando?</button><button class="btn secondary" onclick="go('platephoto')">📷 Aggiungi una foto</button></div>
 <div class="card"><div class="ey">Obiettivi di oggi</div><h2>${fmt(t.calories)} / ${fmt(goals.calories)} kcal</h2><div class="sub"><b>${fmt(remaining)} kcal</b> rimanenti oggi</div><div class="if101-bar big"><i style="width:${pct(t.calories,goals.calories)}%"></i></div></div>
 <div class="card"><div class="ey">Consiglio iCoach</div><h2>Cosa potrei mangiare?</h2><div class="sub">Suggerimenti in base a calorie e macro rimanenti e, quando disponibile, alle scorte HomeStock.</div><button class="btn secondary" onclick="if101Suggest()">💡 Dammi un consiglio</button><div id="if101Suggestion"></div></div>
 <div class="card"><div class="ey">Resoconto di oggi</div>${line('Calorie',t.calories,goals.calories,' kcal')}${line('Proteine',t.protein_g,goals.protein_g,' g')}${line('Carboidrati',t.carbs_g,goals.carbs_g,' g')}${line('Grassi',t.fat_g,goals.fat_g,' g')}</div>`}
 window.if101OpenMeal=function(){if(typeof if100Describe==='function'){if100Describe();setTimeout(()=>{const s=document.getElementById('if100Meal');if(s)s.style.display='none';const st=document.getElementById('if100VoiceState');if(st)st.textContent='Premi Registra vocale e descrivi liberamente quello che stai mangiando.';let b=document.getElementById('if101Mic');if(!b){b=document.createElement('button');b.id='if101Mic';b.className='btn';b.textContent='🎙️ Registra vocale';b.onclick=()=>if100Voice();document.getElementById('if100Text')?.before(b)}} ,50)}};
 window.if101Suggest=async function(){const o=document.getElementById('if101Suggestion');if(!o)return;o.innerHTML='<div class="sub" style="margin-top:10px">Controllo obiettivi, diario e HomeStock…</div>';let hs=[];try{const d=await api('api/homestock/catalog');hs=Array.isArray(d)?d:(d.items||d.products||d.catalog||d.results||d.data||[])}catch(e){}let today={},goals={};try{today=await api('api/nutrition/today')}catch(e){}try{goals=(await api('api/nutrition/goals')).goals||{}}catch(e){}try{const q=`Suggerisci 2 o 3 cose che potrei mangiare adesso. Obiettivi giornalieri: ${JSON.stringify(goals)}. Totali già mangiati: ${JSON.stringify(today.totals||{})}. Scorte HomeStock disponibili: ${JSON.stringify(hs).slice(0,7000)}. Dai priorità agli alimenti realmente presenti in HomeStock. È solo un consiglio, non una dieta obbligatoria. Sii breve e indica calorie approssimative per ogni proposta.`;const d=await api('api/ai-coach/ask',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:q})});o.innerHTML=`<div class="sub" style="margin-top:12px;white-space:pre-wrap">${String(d.answer||'Nessun consiglio disponibile').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}</div>`}catch(e){o.innerHTML='<div class="sub" style="margin-top:10px">Consiglio non disponibile.</div>'}};
 const css=document.createElement('style');css.textContent=`.if101-line{padding:9px 0}.if101-bar{height:7px;border-radius:99px;background:#090b0e;border:1px solid var(--ln);overflow:hidden;margin-top:7px}.if101-bar.big{height:10px;margin-top:12px}.if101-bar i{display:block;height:100%;background:linear-gradient(90deg,var(--green),var(--blue))}`;document.head.appendChild(css);
 const old=window.if80Render;window.if80Render=async function(){if(old){}await render()};const g=window.go;if(g)window.go=function(page){const r=g.apply(this,arguments);if(page==='nutrition')setTimeout(render,80);return r};setTimeout(()=>{if(location.hash==='#nutrition'||document.querySelector('[data-page="nutrition"].active'))render()},500);console.log('[INFORMHA_NUTRITION_HOME] version=0.10.1 add_meal_first=1 goals=1 suggestions=1 summary=1 no_entries_home=1 voice_button=1');
})();